### PR TITLE
dockerised fluxfym application

### LINKED ISSUE #80: run app on 0.0.0.0 instead of 127.0.0.1?
Hi,

I am trying to dockerise this application. is it possible to change the URL:  http://127.0.0.1:7860 to URL:  http://0.0.0.0:7860?

in that case, it would be super easy to manage it using reverse proxy
thanks

### PR DESCRIPTION
**Pull request by fahadshery**
fixes #80 & #67

### CODE REVIEW

**Comment by fahadshery** [comment]
If you don’t set ‘server ip’ within the container then how do you propose to access it from outside the container? I tried running it on 127.0.0.1 but it fails to forward traffic and get response. It just doesn’t work. Therefore in docker world this fixed the issue since docker manages networking for the container.

**Comment by cocktailpeanut** [comment]
if that's the case, please use the environment variables instead of touching the code. As I mentioned, the top priority for this project is it runs on personal computers (windoes, mac, etc.) and I've experienced issues when setting 0.0.0.0 in the past.

There's no reason to hard code it

**Comment by fahadshery** [comment]
> if that's the case, please use the environment variables instead of touching the code. As I mentioned, the top priority for this project is it runs on personal computers (windoes, mac, etc.) and I've experienced issues when setting 0.0.0.0 in the past.
> 
> There's no reason to hard code it

thanks for your msg. please give an example code to use the variable that could be passed down to your main method? I agree that we don't need to hardcode the IP.

**Comment by fahadshery** [comment]
ok I will check using the following `ENV GRADIO_SERVER_NAME="0.0.0.0"`

**Pull request merged**
